### ISSUE TITLE
Error JSON Parsing

### ISSUE THREAD

**Issue by abdullah-abunada** [zachleigh/laravel-lang-bundler#12]
The problem appear when put space between words in Arabic language 

like this =""

<app-header :lang="{&quot;logout&quot;:&quot;\u062e\u0631\u0648\u062c&quot;,&quot;logout_message&quot;:&quot;\u062a\u0645" \u062a\u0633\u062c\u064a\u0644="" \u0627\u0644\u062e\u0631\u0648\u062c="" \u0627\u0644\u0649="" \u0627\u0644\u0644\u0642\u0627&quot;}=""></app-header>

**Comment by abdullah-abunada** [comment]
Or English like this 'Hello World' problem in spaces between words
it's render invalid JSON object

**Comment by zachleigh** [comment]
Hello @abdullah-abunada    
I'm not quite sure I understand the problem. With the 'Hello World' example, how exactly do you get it to trigger the error?

**Comment by abdullah-abunada** [comment]
My language file en/app.php
return [
'home' => 'Home'
'welcome_message' => 'Welcome back',
];

then I make the bundler and passed it to vue component
it give me error in compile vue file 
- invalid expression: :lang="{"logout":"\u062e\u0631\u0648\u062c","logout_message":"\u062a\u0645_\u062a\u0633\u062c\u064a\u0644_\u0627\u0644\u062e\u0631\u0648\u062c_\u0627\u0644\u0649"

because I put spaces between words 'Welcome back' but when I replace space with 'Welcome_back'
it works perfectly.

the problem in parsing the bundler it's understand the space as separator between json key and value.

**Comment by abdullah-abunada** [comment]
I found the problem I passed props from blade to VueJs component like this
<app-header :lang={{ transB('bundles.components.general.app')->toJson() }}></app-header>
this give's error.
so we must pass it like this 
<app-header :lang="{{ transB('bundles.components.general.app')->toJson() }}"></app-header>

Please update the readme file to explain this issue.
Thank you for your time.
Best
